### ISSUE TITLE
Too Slow...

### ISSUE THREAD

**Issue by flexagontnt** [gtw123/OpusSolver#4]
It feels like the bot solves the puzzle too slowly. Can you make it go any faster without changing the MouseUtils.GlobalDragDelay?

**Comment by gtw123** [comment]
It's a trade-off: if you make MouseUtils.GlobalDragDelay smaller (or even 0) it will go faster but is more likely to have problems. If you make it larger it will go slower but is more likely to work correctly.

When I say "have problems" I mean that it will sometimes drag or scroll the mouse too quickly for the game to recognize, and then everything gets out of sync. It depends mostly on the speed of your computer and the size of the puzzle you're trying to solve.

I think the best solution would be to make the bot generate a solution on disk instead of doing it with the mouse (see #2). That would be less interesting to watch, but much faster and more reliable.

**Comment by flexagontnt** [comment]
How do you do it?

**Comment by gtw123** [comment]
I'm not quite sure what you're asking. Do you mean how could we implement https://github.com/gtw123/OpusSolver/issues/2? It would involve writing some code to save a generated solution to Opus Magnum's solution file format, figuring out how to make the bot find the right solution file on disk (using the most recently modified solution file might work OK), and adding some way to let the user tell the bot they want to do this (maybe a second hot key?).

**Comment by flexagontnt** [comment]
How do you generate the solution on disk?

**Comment by gtw123** [comment]
I'm not sure. Someone did make something to read/write solution files but it's in a language I'm not familiar with: https://github.com/fazzone/opus/blob/master/blobs/src/blobs/codec/solution.cljc

**Comment by gtw123** [comment]
Closing this now as it would be resolved by #2 and I don't know of another way to solve it.
